### PR TITLE
Fix bugzilla enrich blocking bug

### PR DESCRIPTION
**Pull request by khalifapro**
Signed-off-by: “khalifapro” <enkhalifapro@yahoo.com>

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Review by ikohobaro — APPROVED** [review]
lgtm

**Comment by ikohobaro** [comment]
Do we need to rebuild sds? cc @lukaszgryglicki

**Comment by lukaszgryglicki** [comment]
Si, will do tmorrow.

**Comment by lukaszgryglicki** [comment]
New SDS images were built after the merge. New SDS syncs will use this.

**Pull request merged**
