### PR TITLE
Bugfix Da 3594

### PR DESCRIPTION
**Pull request by lfpratik**

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
Is this for `test` or `prod`? You should create a PR against test or prod or both...

**Comment by lfpratik** [comment]
@lukaszgryglicki, it was for both

**Comment by lukaszgryglicki** [comment]
So there should be a PR for `test` and `prod` too, and note that `test` runs `da-ds` git globally while `prod` uses `p2o`.

**Comment by lukaszgryglicki** [comment]
Anyway, I will update both test and prod, because even if prod is not using this (it still uses p2o) it *will* use `da-ds` in the future...

**Pull request merged**
